version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'sunday'
      labels:
          - 'npm dependencies'
      rebase-strategy: 'auto'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'sunday'
      labels:
          - 'actions'
