name: General inquiry
description: Start a discussion not related to a bug or feature request
title: '[General Inquiry]: '
labels: ['question']

body:
    - type: textarea
      id: general-inquiry
      attributes:
          label: What is your general inquiry?
          description: Please provide as much detail as possible
      validations:
          required: true
