/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CumulativeLayoutShiftEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  /**
   * Largest burst of unexpected layout shifts during a page's lifespan
   */
  value: number;
  /**
   * Attributions for CLS
   */
  attribution?: {
    /**
     * First element in the largest layout shift contributing to CLS score
     */
    largestShiftTarget?: string;
    /**
     * Value of CLS' single largest shift
     */
    largestShiftValue?: number;
    /**
     * DOMHighResTimeStamp of CLS' single largest shift
     */
    largestShiftTime?: number;
    /**
     * LoadState during CLS' single largest shift
     */
    loadState?: "loading" | "dom-interactive" | "dom-content-loaded" | "complete";
  };
}
