/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FirstInputDelayEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  /**
   * Time from first user interaction until the main thread is next idle
   */
  value: number;
  /**
   * Attributions for FID
   */
  attribution?: {
    /**
     * Selector of the element targeted by first user interaction
     */
    eventTarget: string;
    /**
     * Type of event dispatched by first user interaction
     */
    eventType: string;
    /**
     * Timestamp of user first user interaction
     */
    eventTime: number;
    /**
     * LoadState of the document during first user interaction
     */
    loadState: "loading" | "dom-interactive" | "dom-content-loaded" | "complete";
  };
}
