/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  trace_id?: string;
  segment_id?: string;
  request: {
    method: string;
    url?: string;
  };
  response?: {
    status: number;
    statusText?: string;
  };
  error?: {
    /**
     * JSErrorEvent schema version.
     */
    version?: string;
    /**
     * Error type (eg., TypeError, ParseError, etc).
     */
    type?: string;
    message?: string;
    filename?: string;
    lineno?: number;
    colno?: number;
    stack?: string;
  };
}
