/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LargestContentfulPaintEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  /**
   * Time until the largest element before first user interaction is rendered
   */
  value: number;
  /**
   * Attributions for CLS
   */
  attribution?: {
    /**
     * CSS selector of LCP resource
     */
    element?: string;
    /**
     * URL source of the LCP resource's image, if any
     */
    url?: string;
    /**
     * Duration until first byte of response
     */
    timeToFirstByte: number;
    /**
     * Duration after TTFP until LCP resource begins loading
     */
    resourceLoadDelay: number;
    /**
     * Duration loading the LCP resource
     */
    resourceLoadTime: number;
    /**
     * Duration rendering the LCP resource
     */
    elementRenderDelay: number;
    /**
     * Event id of the navigation event for the current page
     */
    navigationEntry?: string;
    /**
     * Event id of the resource event for the LCP resource, if any
     */
    lcpResourceEntry?: string;
  };
}
