/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NavigationEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  initiatorType: "navigation" | "route_change";
  /**
   * An unsigned short which indicates how the navigation to this page was done. Possible values are:TYPE_NAVIGATE (0), TYPE_RELOAD (1), TYPE_BACK_FORWARD (2), TYPE_RESERVED (255)
   */
  navigationType?: "navigate" | "reload" | "back_forward" | "reserved";
  startTime: number;
  unloadEventStart?: number;
  promptForUnload?: number;
  redirectCount?: number;
  redirectStart?: number;
  redirectTime?: number;
  workerStart?: number;
  workerTime?: number;
  fetchStart?: number;
  domainLookupStart?: number;
  dns?: number;
  nextHopProtocol?: string;
  connectStart?: number;
  connect?: number;
  secureConnectionStart?: number;
  tlsTime?: number;
  requestStart?: number;
  timeToFirstByte?: number;
  responseStart?: number;
  responseTime?: number;
  domInteractive?: number;
  domContentLoadedEventStart?: number;
  domContentLoaded?: number;
  domComplete?: number;
  domProcessingTime?: number;
  loadEventStart?: number;
  loadEventTime?: number;
  duration: number;
  headerSize?: number;
  transferSize?: number;
  compressionRatio?: number;
  navigationTimingLevel?: number;
}
