/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PageViewEvent {
  /**
   * Schema version.
   */
  version?: "1.0.0";
  pageId: string;
  pageInteractionId?: string;
  interaction?: number;
  parentPageInteractionId?: string;
  timeOnParentPage?: number;
  referrer?: string;
  referrerDomain?: string;
}
