/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PerformanceNavigationTimingEvent {
  name?: string;
  entryType: "navigation";
  /**
   * StartTime value is always '0' for PerformanceNavigationTimingEvents created by the PerformanceAPI. However, non-W3C 'route_changes' created by RUM's polyfill for SinglePageApplications can have startTimes >= 0.
   */
  startTime: number;
  duration: number;
  /**
   * InitiatorType value is always 'navigation' for PerformanceNavigationTimingEvents created by the PerformanceAPI. However, RUM adds the non-W3C concept 'route_change' as a polyfill because the PerformanceAPI currently does not support Single Page Applications.
   */
  initiatorType: "navigation" | "route_change";
  nextHopProtocol?: string;
  workerStart?: number;
  redirectStart?: number;
  redirectEnd?: number;
  fetchStart?: number;
  domainLookupStart?: number;
  domainLookupEnd?: number;
  connectStart?: number;
  connectEnd?: number;
  secureConnectionStart?: number;
  requestStart?: number;
  responseStart?: number;
  responseEnd?: number;
  transferSize?: number;
  encodedBodySize?: number;
  decodedBodySize?: number;
  domComplete?: number;
  domContentLoadedEventEnd?: number;
  domContentLoadedEventStart?: number;
  domInteractive?: number;
  loadEventEnd?: number;
  loadEventStart?: number;
  redirectCount?: number;
  type?: "navigate" | "reload" | "back_forward" | "prerender";
  unloadEventEnd?: number;
  unloadEventStart?: number;
}
