/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PerformanceResourceTimingEvent {
  name?: string;
  entryType: "resource";
  startTime: number;
  duration: number;
  connectStart?: number;
  connectEnd?: number;
  decodedBodySize?: number;
  domainLookupEnd?: number;
  domainLookupStart?: number;
  encodedBodySize?: number;
  fetchStart?: number;
  initiatorType?:
    | "audio"
    | "beacon"
    | "body"
    | "css"
    | "early-hint"
    | "embed"
    | "fetch"
    | "frame"
    | "iframe"
    | "icon"
    | "image"
    | "img"
    | "input"
    | "link"
    | "navigation"
    | "object"
    | "ping"
    | "script"
    | "track"
    | "video"
    | "xmlhttprequest"
    | "other";
  nextHopProtocol?: string;
  redirectEnd?: number;
  redirectStart?: number;
  renderBlockingStatus?: string;
  requestStart?: number;
  responseEnd?: number;
  responseStart?: number;
  secureConnectionStart?: number;
  transferSize?: number;
  workerStart?: number;
}
