/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ResourceEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  /**
   * Page URL
   */
  targetUrl?: string;
  initiatorType: string;
  startTime?: number;
  redirectStart?: number;
  redirectTime?: number;
  workerStart?: number;
  workerTime?: number;
  fetchStart?: number;
  domainLookupStart?: number;
  dns?: number;
  nextHopProtocol?: string;
  connectStart?: number;
  connect?: number;
  secureConnectionStart?: number;
  tlsTime?: number;
  requestStart?: number;
  timeToFirstByte?: number;
  responseStart?: number;
  responseTime?: number;
  duration: number;
  headerSize?: number;
  transferSize?: number;
  compressionRatio?: number;
  fileType: string;
}
