/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RRWebEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  /**
   * Unique session identifier.
   */
  sessionId: string;
  /**
   * Unique recording identifier.
   */
  recordingId: string;
  /**
   * Array of rrweb events with timestamps.
   */
  events: {
    [k: string]: unknown;
  }[];
  /**
   * Recording metadata and context.
   */
  metadata: {
    /**
     * Array of correlated RUM event IDs.
     */
    correlatedRumEvents?: string[];
    /**
     * Timestamp when recording started.
     */
    recordingStartTime: number;
    /**
     * Timestamp when recording ended.
     */
    recordingEndTime?: number;
    /**
     * User agent string.
     */
    userAgent: string;
    /**
     * Viewport dimensions.
     */
    viewport: {
      /**
       * Viewport width in pixels.
       */
      width: number;
      /**
       * Viewport height in pixels.
       */
      height: number;
    };
    /**
     * Page URL when recording started.
     */
    url: string;
    /**
     * Page title when recording started.
     */
    title: string;
    /**
     * Recording sampling rate (0-1).
     */
    samplingRate?: number;
  };
}
