/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SessionReplayEvent {
  /**
   * Schema version.
   */
  version: "1.0.0";
  /**
   * Batch of rrweb recording events.
   */
  events: {
    /**
     * rrweb event type.
     */
    type: number;
    /**
     * Unix timestamp in milliseconds.
     */
    timestamp: number;
    /**
     * rrweb event payload.
     */
    data: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  /**
   * Number of events in this batch.
   */
  eventCount: number;
}
