#!/bin/bash

lib="src/event-schemas/*.json"
regex="(.*)\.json"

for schema in $lib
do
  file=$(basename $schema)
  if [[ $file =~ $regex ]]
  then
    npx json-schema-to-typescript --input "$schema" --output "src/events/${BASH_REMATCH[1]}.ts"
  fi
done
